a, b, c = input().split()
a = float(a)
b = float(b)
c = float(c)
d, e, f = input().split()
d = float(d)
e = float(e)
f = float(f)
soma = (c * b) + (f * e)
print(f'VALOR A PAGAR: R$ {soma:.2f}')
